// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9JvN8Q4NUKXVXyNx0aAtWxSEeB2dO-nQ',
    appId: '1:337280794167:web:f7f4ba2098d79d08ca89b2',
    messagingSenderId: '337280794167',
    projectId: 'chatapp-f149b',
    authDomain: 'chatapp-f149b.firebaseapp.com',
    storageBucket: 'chatapp-f149b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl2lco2u1c3FYlfgJpxKPCl_lGqyu-Wzs',
    appId: '1:337280794167:android:2f7adefacd812c4dca89b2',
    messagingSenderId: '337280794167',
    projectId: 'chatapp-f149b',
    storageBucket: 'chatapp-f149b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgLPBLI4TapsVg6kMCRLQUt4jbVHfF6M',
    appId: '1:337280794167:ios:c1d406ea844c2f64ca89b2',
    messagingSenderId: '337280794167',
    projectId: 'chatapp-f149b',
    storageBucket: 'chatapp-f149b.appspot.com',
    androidClientId: '337280794167-tkd8lg0u95129g9mfoj9s2f2sqinrqoo.apps.googleusercontent.com',
    iosClientId: '337280794167-9g9ko4e9qirt9o3mqp273hofkta7oe1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chats',
  );
}
